// <auto-generated />
using System;
using Bachelor_s_Point.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bachelor_s_Point.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526082045_AddDivisionAndDistrictToRoom")]
    partial class AddDivisionAndDistrictToRoom
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bachelor_s_Point.Models.ChatMessage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Content")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("RoomSelectionId")
                    .HasColumnType("int");

                b.Property<int>("SenderId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RoomSelectionId");

                b.HasIndex("SenderId");

                b.ToTable("ChatMessages");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.KycVerification", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("FullNameOnNid")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NidBackImagePath")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NidFrontImagePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("NidNumber")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("ReviewedByAdminId")
                    .HasColumnType("int");

                b.Property<DateTime?>("ReviewedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("RejectionReason")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("SubmittedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("UserPhotoPath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId")
                    .IsUnique();

                b.ToTable("KycVerifications");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.LoginHistory", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("LoginAt")
                    .HasColumnType("datetime2");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("LoginHistories");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.PasswordResetToken", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("ExpiresAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("PasswordResetTokens");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.PendingRegistration", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Otp")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("OtpExpiresAt")
                    .HasColumnType("datetime2");

                b.Property<int>("VerificationAttempts")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("PendingRegistrations");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.Role", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("RoleDescription")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("RoleName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Roles");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.Room", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("ApprovedAt")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("District")
                    .HasMaxLength(60)
                    .HasColumnType("nvarchar(60)");

                b.Property<string>("Division")
                    .HasMaxLength(60)
                    .HasColumnType("nvarchar(60)");

                b.Property<bool>("IsApproved")
                    .HasColumnType("bit");

                b.Property<bool>("IsAvailable")
                    .HasColumnType("bit");

                b.Property<string>("Location")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int?>("MaidCostPerMonth")
                    .HasColumnType("int");

                b.Property<int?>("MealCostPerMonth")
                    .HasColumnType("int");

                b.Property<int>("Price")
                    .HasColumnType("int");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.Property<int?>("WifiCost")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Rooms");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.RoomImage", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("DisplayOrder")
                    .HasColumnType("int");

                b.Property<string>("ImagePath")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("bit");

                b.Property<int>("RoomId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RoomId");

                b.ToTable("RoomImages");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.RoomSelection", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("RoomId")
                    .HasColumnType("int");

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("RoomId");

                b.HasIndex("UserId");

                b.ToTable("RoomSelections");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DateOfBirth")
                    .HasColumnType("date");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ProfilePictureUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RoleId")
                    .HasColumnType("int");

                b.Property<string>("UserName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.HasIndex("RoleId");

                b.ToTable("Users");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.ChatMessage", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.RoomSelection", "RoomSelection")
                    .WithMany("Messages")
                    .HasForeignKey("RoomSelectionId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bachelor_s_Point.Models.User", "Sender")
                    .WithMany()
                    .HasForeignKey("SenderId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("RoomSelection");

                b.Navigation("Sender");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.KycVerification", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.User", "User")
                    .WithOne("KycVerification")
                    .HasForeignKey("Bachelor_s_Point.Models.KycVerification", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.LoginHistory", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.User", "User")
                    .WithMany("LoginHistories")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.PasswordResetToken", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.User", "User")
                    .WithMany("PasswordResetTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.Room", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.User", "Owner")
                    .WithMany("Rooms")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Owner");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.RoomImage", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.Room", "Room")
                    .WithMany("Images")
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Room");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.RoomSelection", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.Room", "Room")
                    .WithMany("Selections")
                    .HasForeignKey("RoomId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Bachelor_s_Point.Models.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Room");

                b.Navigation("User");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.User", b =>
            {
                b.HasOne("Bachelor_s_Point.Models.Role", "Role")
                    .WithMany("Users")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Role");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.Role", b =>
            {
                b.Navigation("Users");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.Room", b =>
            {
                b.Navigation("Images");

                b.Navigation("Selections");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.RoomSelection", b =>
            {
                b.Navigation("Messages");
            });

            modelBuilder.Entity("Bachelor_s_Point.Models.User", b =>
            {
                b.Navigation("KycVerification");

                b.Navigation("LoginHistories");

                b.Navigation("PasswordResetTokens");

                b.Navigation("Rooms");
            });
#pragma warning restore 612, 618
        }
    }
}